name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: ./setup.sh
      - name: Type check
        run: npm run type-check --prefix frontend
      - name: Lint
        run: npm run lint --prefix frontend
      - name: Run tests
        run: npm test --prefix frontend

  build-and-analyze:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: ./setup.sh
      - name: Build and analyze bundle
        run: |
          cd frontend
          npm run analyze
      - name: Bundle size check
        run: |
          cd frontend
          CURRENT_SIZE=$(du -sk .next/static | cut -f1)
          THRESHOLD=5000  # 5MB
          if [ $CURRENT_SIZE -gt $THRESHOLD ]; then
            echo "❌ Bundle size ${CURRENT_SIZE}KB exceeds ${THRESHOLD}KB"
            exit 1
          else
            echo "✅ Bundle size ${CURRENT_SIZE}KB is within threshold"
          fi

  performance-audit:
    runs-on: ubuntu-latest
    needs: build-and-analyze
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: ./setup.sh
      - name: Build project
        run: |
          cd frontend
          npm run build
          npm start &
          sleep 10
      - name: Run Lighthouse audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './lighthouserc.json'
          temporaryPublicStorage: true
